-- 코드를 입력하세요
SELECT HISTORY_ID --자동차 대여 기록 ID
     , CAR_ID --자동차 ID
     , TO_CHAR(START_DATE, 'YYYY-MM-DD') AS START_DATE --대여 시작일
     , TO_CHAR(END_DATE, 'YYYY-MM-DD') AS END_DATE --대여 종료일
     , CASE WHEN (END_DATE - START_DATE +1) >= 30 THEN '장기 대여'
         ELSE '단기 대여'
       END AS RENT_TYPE
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE,'YYYYMMDD') LIKE '202209%'
  ORDER BY HISTORY_ID DESC