-- 코드를 입력하세요
--보호 시작일 I.DATETIME
--입양일 O.DATETIME
--보호 시작일보다 입양일이 더 빠른
SELECT 
      I.ANIMAL_ID
    , I.NAME
    FROM ANIMAL_INS I
            JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME;