-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
SUBSTR(DATE_OF_BIRTH,1,10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
AND NOT TLNO IS NULL
AND DATE_OF_BIRTH LIKE '%03%'
ORDER BY MEMBER_ID ASC;